- 0.15/Dockerfile
- README.md
Bumped the version number in the `Dockerfile` and README, and updated the SHA1, hopefully that's all that's needed for a version bump.
> Update to 0.15.4

- 0.15/docker-entrypoint.sh
- README.md
Version 0.15 added a bunch of new map settings in a third configuration file.  Now you can control the evolution rate, biter expansion, pollution spread, and more.
> Add map-settings.json config file

- 0.15/Dockerfile
- 0.15/docker-entrypoint.sh
I stumbled over this when I tried to run multiple servers with "network_mode: host", which I need so they show up in the LAN browser.
> Allow to define RCON port as well

- 0.15/Dockerfile
When starting the container with `docker run -d -u $(id -u factorio):$(id -g factorio) ...`, permission is denied upon trying to create `/opt/factorio/.lock` file.
This permission tweak will allow caller to pass desired user from host to container such that the permissions are retained correctly when games are saved to the mount.
Also, it just feels wrong to run factorio as root, container or not.  :)
> Allowing non-root user to run factorio

- README.md
Make sure users of 1.16 don't get stopped by weird permissions errors created by #91 because factorio is no longer run as root in the container.
> Document the required permissions change in 1.16+

- 0.16/Dockerfile
When using named containers in docker compose, it creates them with root and the factorio docker container fails to start because it doesn't have write permissions. Reproduce by using the following docker-compose file:
version: '3.2'
services:
server:
image: dtandersen/factorio:0.16.7
volumes:
- logs:/var/log
- data:/factorio
ports:
- "34197:34197/udp"
- "27015:27015/tcp"
volumes:
logs:
data:
With this proposed change, the /factorio folder is created *before* it is made a volume. This causes docker to correctly preserve the permissions, the docker-compose file above works now.
This is related to https://github.com/dtandersen/docker_factorio_server/issues/91 and maybe also makes https://github.com/dtandersen/docker_factorio_server/pull/99 obsolete.
> Fix volume permissions for docker-compose

- 0.17/files/docker-entrypoint.sh
- README.md
The `admins` configuration in server-settings.json doesn't do anything anymore, and has been replaced by adminlist. Additionally, banlist is the new way to handle bans. This adds support for these features.
> Adding support for 0.17's new banlist and adminlist options

- 0.17/files/docker-update-mods.sh
- 0.17/files/update-mods.sh
I've tried the script but faced an issue with mods which are containing spaces in their names. It was quite tricky and this is my working solution to also support this scenarios. 
What I've done:
* I've added a bit more sanity checks and modified/added some output messages.
* Reduced two `curl` calls for mod info to one single one - speeding up the whole process, and lowering amount of requests to Factorio servers.
* Changing the `for` to `while` was required as the `for` was splitting up at each spaces too, being one reason it didn't work earlier.
* In this current commit I've commented-out three lines at the end which causes the script to stop once one mod cannot be updated. IMHO it might be more useful to keep updating, e.g. in cases a plugin simply just got removed and unnecessary …
> Updated script to support mods with spaces in name

- 0.17/files/docker-entrypoint.sh
Add the `-o` switch to usermod and groupmod in order to allow non-unique IDs to be specified. 
This is in relation to issue #231
> Fix conflicting group IDs

- .travis.yml
- 0.17/files/docker-entrypoint.sh
- build.sh
This is going to implement some of the requested feature from over here https://github.com/Fankserver/docker_factorio_server_test/issues/3
To see how travis works with those changes take a look here https://travis-ci.org/SuperSandro2000/docker_factorio_server/branches or create some test PR's here https://github.com/SuperSandro2000/docker_factorio_server
These things are still open for @Fank
> Advance CI features

- 0.16/Dockerfile
- 0.16/files/docker-entrypoint.sh
I'm running Factorio with shared folders on an instance where I can't set the UID/GID. It looks like this is already setup for latest so wanted to be able to run the same way on stable as well.
https://github.com/factoriotools/factorio-docker/blob/44371283b6dbff377ad0bf55c1d9365289b2794a/0.17/Dockerfile#L19-L20
> Allow puid/pgid to be set as environment vars on stable

- 0.17/Dockerfile
- 0.17/docker-compose.yml
- 0.17/files/docker-entrypoint.sh
- 0.17/files/docker-update-mods.sh
- 0.17/files/update-mods.sh
- README.md
Based on work from https://github.com/ALovedOne and https://github.com/patschi
Needs proper testing!
> Rebase modupdater

- 0.17/Dockerfile
- README.md
This updates the docker image to 0.17.59.
Do squash on merge if needed (I did this via the web-ui).
> Update to 0.17.59

- 0.17/files/docker-entrypoint.sh
- README.md
This change enables specifying a specific save to use via the $SAVE_NAME
variable when $ENABLE_SERVER_LOAD_LATEST is false. Additionally, you can
set $ENABLE_GENERATE_NEW_MAP_SAVE to generate a map for $SAVE_NAME if
one does not already exist.
I've been using this a bit lately to swap between a few saves on my server, and
to make it easier to generate new maps by just changing my `SAVE_NAME`.
Let me know what you think.
> Allow configuring factorio server to run with a specific save through environment variables

- 0.18/files/update-mods.sh
custom mods are defined by mods not found in the mod registry.
uses jq -e to provide an exit code if .name is found or not
> Fixes #306 by skipping custom mods

- README.md
The environment variables listed in the README for handling new save files don't appear to work. Looking at the actual docker-entrypoint.sh, they have different names.
> Fix save file environment variables in README.md.

- 0.18/Dockerfile
Update alpine-glibc image to 3.11 as 3.9 has not received updates for more than a year. 
Tested with my factorio installation.
> update alpine-glibc image to 3.11

- 0.17/files/scenario.sh
- 0.18/files/scenario.sh
Let scenario.sh script to use map-gen-settings.json/map-settings.json located in config directory.
I tried the same with scenario2map.sh script, but it appears that factorio binary ignores map-gen-settings arguments when scenario2map argument is used. Therefore, only scenario.sh is updated here. (related: https://forums.factorio.com/viewtopic.php?t=69377 )
> Let scenario.sh script to use map-gen-settings.json/map-settings.json located in config directory.

- 0.17/Dockerfile
- 0.18/Dockerfile
Create symlink for save directory so that save files generated from scenario.sh/scenario2map.sh scripts will be correctly persisted in the mounted volume, instead of in /opt/factorio/saves directory which is ephemeral.
> Save op fix for scenario.sh and scenario2map.sh.

- 1.1/Dockerfile
Resolve #397 by adding Factorio 1.1.36 support
> Update Dockerfile to support Factorio 1.1.36

- .github/workflows/docker.yml
- .github/workflows/docker_push.yml
- build.py
- buildinfo.json
- docker/Dockerfile
- templates/Dockerfile.jinja2
This is a rework of #404 which switches from sha1 to sha256.
This also drops the usage of the jinja templating in favour of the docker build-args.
- https://github.com/factoriotools/factorio-docker/pull/382#issuecomment-911659518
> update to sha256 for checksum verification

- .github/dependabot.yml
- buildinfo.json
~I noticed that there were open PRs for dependencies on 0.14 to 0.18 but nothing for 1.0 and 1.1.~
This is now updated to check in the ./docker directory now that there is only a single Dockerfile.
> Update dependabot to check in ./docker

- README.md
- docker/Dockerfile
- docker/docker-compose.yml
Related: https://github.com/factoriotools/factorio-docker/issues/412
This should fix the issue where some people are seeing this error message when using a docker compose setup.
```
ERROR: Service 'factorio' failed to build: failed to process "${VERSION:?}": unsupported modifier (?) in substitution
```
I could not find the exact version where docker changed or added support for the variable substitution, so the next best thing was to not use it and add in a check for the value.
I did find that docker-compose >= 1.6.0 is needed because this project is using v2 of the compose spec
- https://github.com/docker/compose/releases/tag/1.6.0
The other option I see here is to have buildinfo.json added into the container and then have the docker file determine which version to install when `VERSION` …
> support older versions of docker and docker-compose

- .github/workflows/docker-description.yml
- .github/workflows/docker_push.yml
When I have been syncing my fork I noticed that the GitHub actions were running on the master branch and failing.
This changes the workflows so that it will only try pushing if the secrets are specified.
You can see some example flows here where I was forcing it to run on any push for testing
- https://github.com/perobertson/factorio-docker/actions
Ideally I would use `jobs.<job_id>.if` to specify the condition, but I could not find a way to see if the secrets were available.
The next best thing was to use `jobs.<job_id>.steps.if` and check if an environment was available.
- https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
> Skip pushing to docker hub when user and pass are not specified

- docker/Dockerfile
Adding configurable retries to the curl download of the headless server tarball.
> Update Dockerfile - add curl retries (#444)

- README.md
- docker/docker-compose.yml
- docker/files/docker-entrypoint.sh
Factorio allows setting an IP address to bind to in the `--bind` switch.
The current configuration allows setting the port, this PR also allows setting the IP using the `ADDR` envvar.
The behavior is as expected, setting `--port 1000 --bind ::1` will bind Factorio to `::1:1000`.
For example it allows restricting the IPv6 address used in server responses to allow UDP reverse proxies to work. Without such restriction the proxy may fail to recognize upstream responses due to a different IP being used for response.
> Add an IP bind param to the entrypoint

- README.md
- docker/files/docker-entrypoint.sh
Fixes https://github.com/factoriotools/factorio-docker/issues/460
I don't know when that argument has been introduced, that's why the `Available In` section is currently blank
> Add --console-log support

- update.sh
Hey there, we're publishing the official sha256sum on factorio.com, so downloading the latest release from our CDN is not necessary.
> Use official sha256 endpoint for update check

- .github/workflows/docker.yml
- .github/workflows/docker_push.yml
- README.md
- build.py
- docker/Dockerfile
- docker/files/docker-entrypoint.sh
In my quest to [run factorio headless server on raspberrry pi](https://github.com/mcrossen/factorio-pi) I came across '[box64](https://github.com/ptitSeb/box64)'. What's nice about box64 is it doesn't require emulating an entire ARM host, so it should be more performant than my other attempts.
In order for this to work, we need a different docker base image. [PR#469](https://github.com/factoriotools/factorio-docker/pull/469) already fixes this. I see the PR is approved, but not merged. I copied the changes from that PR into my first commit, so the changed files of this PR will look a lot cleaner once that PR is merged.
I divided the changes into two commits: dockerfile changes, and build automation changes.
Changes to the dockerfile allow the image to be built on arm64 hosts. Go ahead and …
> add support for ARM

- docker/Dockerfile
Having a label on the factorio container which stores the factorio version of the container is useful for automation and debugging purposes. Furthermore it is a simple addition to the dockerfile.
> Container label for factorio version

- docker/Dockerfile
As discussed in #506, this change re-uses intermediate stages for apt update, apt install and box64 install, and subsequent clean-up.
The docker image size stays the same, but the build is faster as the operations mentioned above are re-used for all images.
> Improve image stages

- build.py
Sort versions in buildinfo.json before building and always build newer versions first.
> Build in reverse order of versions

- docker/files/update-mods.sh
This pull request includes updates to the `update_mod()` function in the `docker/files/update-mods.sh` script to improve the clarity of log messages during the mod update process.
Improvements to log messages:
* Clarified the log message to include the Factorio version when checking for mod updates. (`docker/files/update-mods.sh`)
* Enhanced the log message to specify the filename being downloaded. (`docker/files/update-mods.sh`)
Related #517 #468
> Improve logging in updating mods

- README.md
- docker/files/docker-dlc.sh
- docker/files/docker-entrypoint.sh
This pull request includes updates to the `README.md` file for better formatting and the addition of a new environment variable, as well as new scripts to manage DLC mods in the Docker setup.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L264-R264): Improved table formatting for environment variables and added a new variable `DLC_SPACE_AGE` to enable or disable DLC mods. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L264-R264) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L273-R275)
* [`docker/files/docker-dlc.sh`](diffhunk://#diff-1d00cf54e20862293ddcb244a1557d9bb2a2b77e92eca21161323c51944c3605R1-R38): Added a new script to enable or disable DLC mods based …
> Added DLC_SPACE_AGE environment variable

- README.md
- docker/files/docker-entrypoint.sh
Pass the `MODS` environment variable to the Factorio executable with the argument `--mod-directory`   
This make it possible to change the mod directory by only changing the variable.
The recent change for version 2.0.9 introduced a script to enable/disable Space Age mods. This broke my setup because I was using the argument `--mod-directory` to use a different folder. The script `docker-dlc.sh` couldn't find any `mod-list.json` file.
As a workaround without this change, it's possible to set the `MODS` variable and also set the `--mod-directory` argument. With this change, only the setting the `MODS` variable is required.
> Add documentation for env variable MODS and make it change mod directory

- docker/files/docker-dlc.sh
This pull request includes a small change to the `docker/files/docker-dlc.sh` file. The change ensures that the `mod-list.json` file is created if it does not already exist.
* [`docker/files/docker-dlc.sh`](diffhunk://#diff-1d00cf54e20862293ddcb244a1557d9bb2a2b77e92eca21161323c51944c3605R7-R11): Added a check to create the `mod-list.json` file with a default configuration if it doesn't exist.
Fixes #522
> Create base mod-list.json if it does not exist

- README.md
- docker/files/docker-dlc.sh
fix #529
Instead of only `true` or `false`, the environment variable `DLC_SPACE_AGE` can be set to the name of the Space Age mods to enable. The unlisted Space Age mods are disabled.
Any combination of the Space Age mods can be used:
- `space-age elevated-rails quality`
- `space-age elevated-rails `
- `space-age quality`
- `space-age`
- `elevated-rails quality`
- `elevated-rails`
- `quality`
> Change DLC_SPACE_AGE to enable specific Space Age mods

- docker/files/docker-entrypoint.sh
With the current use of relative paths in the Docker entrypoint script the user is _forced_ to run the `docker-entrypoint.sh` script from the root of the filesystem in the container. While this is fine for production I'm trying to use the Factorio container image as a basis for a devcontainer for mod development and would prefer to not have to `cd` to the root of the filesystem to start the server.
I've tested this locally by building the container image and starting the server from both the root of the filesystem as well as from another directory (in my case I used `/tmp`) and saw that I was able to start the server from either of them.
> Use Absolute Paths over Relative Paths for Scripts in Entrypoint

- docker/docker-compose.yml
This pull request includes a change to the `docker/docker-compose.yml` file to provide an option for using the host's network stack, which can be necessary for certain setups such as NAS.
Networking configuration:
* [`docker/docker-compose.yml`](diffhunk://#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03R25-R29): Added commented-out configuration for `extra_hosts` to enable the use of the host's network stack.
Fixes #536
> Added extra_host example for NAS

- docker-compose.yml
Fixes watchtower also updating other containers because the scope is not enabled.
> Fix watchtower also updating other containers
