factoriotools/factorio-docker

0.14/Dockerfile
README.md

Not sure how to test this exactly but, it seems to work locally. Hopefully, I did this right but, let me know if I missed anything!

Bump version to 0.14.22

---

0.15/Dockerfile
0.15/start.sh
README.md

Let me know if I missed anything!

Update 0.15.x branch to 0.15.3

---

0.15/Dockerfile
README.md

This pull request updates the Dockerfile to support **v0.15.10-experimental** and was automatically created by [Game-Watcher](https://github.com/bkuhl/game-watcher).

Update to v0.15.10-experimental

---

0.15/Dockerfile
README.md

This pull request updates the Dockerfile to support **v0.15.11-experimental** and was automatically created by [Game-Watcher](https://github.com/bkuhl/game-watcher).

Update to v0.15.11-experimental

---

0.15/build.sh
0.15/clean.sh
0.15/docker-compose.yml
0.15/docker-entrypoint.sh
0.15/run.sh
0.15/start.sh

Thinking server-id.json will keep the server as a favorite after the container is destroyed.

server-id / banlist / docker-compose

---

0.15/Dockerfile
README.md

This pull request updates the Dockerfile to support **v0.15.12-experimental** and was automatically created by [Game-Watcher](https://github.com/bkuhl/game-watcher).

Update to v0.15.12-experimental

---

0.15/Dockerfile
README.md

This pull request updates the Dockerfile to support **v0.15.13-experimental** and was automatically created by [Game-Watcher](https://github.com/bkuhl/game-watcher).

Update to v0.15.13-experimental

---

0.15/Dockerfile

Probably not entirely necessary, but it's a nice hardening step

Running factorio server as non-root

---

0.16/Dockerfile

Fix adduser

---

0.16/Dockerfile
0.16/docker-entrypoint.sh
0.16/scenario.sh
0.16/scenario2map.sh
README.md

Updated to create new Scenarios and Entrypoints folders to facilitate launching Scenarios. Includes sample entrypoints. Only for 0.16

Add Scenarios Folder, Alternate Entrypoints Folder

---

0.16/Dockerfile
0.16/files/docker-entrypoint.sh
README.md

Added catch all to allow custom options for factorio

---

0.17/dockerfile

Updated to Alpine 3.9 & added preliminary support for the 0.17 headless binary (once released) 💥

Create 0.17 dockerfile

---

0.17/Dockerfile
0.17/files/docker-entrypoint.sh

Currently the map generator is crashing:
```
factorio_1  | + /opt/factorio/bin/x64/factorio --create /factorio/saves/_autosave1.zip --map-gen-settings /factorio/config/map-gen-settings.json --map-settings /factorio/config/map-settings.json
factorio_1  |    0.000 2019-02-26 19:52:22; Factorio 0.17.0 (build 42971, linux64, headless)
factorio_1  |    0.000 Operating system: Linux
factorio_1  |    0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--create" "/factorio/saves/_autosave1.zip" "--map-gen-settings" "/factorio/config/map-gen-settings.json" "--map-settings" "/factorio/config/map-settings.json"
factorio_1  |    0.000 Read data path: /opt/factorio/data
factorio_1  |    0.000 Write data path: /opt/factorio [32698/40188MB]
factorio_1  |    0.000 Binaries path: /opt/factorio/bin …
```

0.17 debugging

---

0.17/Dockerfile
README.md

The idea described in #197 is great but lacks the missing envsubst util. I added it to the latest Dockerfile and will add an example to the ticket.

#197: Enable envsubst

---

0.17/Dockerfile
README.md

I know pascaldulieu already made one, but there's conflicts. This one should merge automatically.

Update to 0.17.13

---

0.17/Dockerfile
0.17/docker-compose.yml
0.17/files/docker-entrypoint.sh
0.17/files/docker-update-mods.sh
0.17/files/update-mods.sh
README.md

Should be backwards compatible with existing functionality since you have to opt in.
Had to update the Docker file to keep curl around and added a the jq package.

Add script to optionally automatically update mods in server start

---

0.17/Dockerfile
0.17/docker-compose.yml
0.17/files/docker-entrypoint.sh

This PR is created to satisfy the issue #214.
Essentially allows the setting of a PUID/PGID variable, then modifies the factorio user and group to match these new values. 
Also I added these variables to the Dockerfile to enable changing the defaults with arguments.
I have not updated the readme to include references to this change, should you want me to, then let me know.

Add support for changing UID/GID

---

README.md

As per https://github.com/dtandersen/docker_factorio_server/issues/235

Add AWS deployment repo Link.

---

0.16/files/scenario.sh
0.16/files/scenario2map.sh
0.17/files/scenario.sh
0.17/files/scenario2map.sh

Renamed local variable `$SCENARIO` to `$SERVER_SCENARIO`

Fixed naming of `$SCENARIOS`

---

0.17/files/docker-entrypoint.sh

fixing #250 (starting from 0.17.37 this time)

fix for #250 Update docker-entrypoint.sh

---

0.17/files/docker-entrypoint.sh

Quotes did not need to be there. Tested.

fix for .tmp.zip saves not being deleted on start

---

0.17/Dockerfile

Shouldn't break anything but did a PR just to be sure.

Quote all vars in Dockerfile

---

0.17/Dockerfile
README.md

https://www.reddit.com/r/factorio/comments/c4qf6n/version_01752/

Update to 0.17.52

---

0.17/Dockerfile
README.md

https://www.reddit.com/r/factorio/comments/c928b4/version_01754/

Update to 0.17.54

---

0.17/files/update-mods.sh

URL encode spaces

---

0.17/Dockerfile
0.17/files/config.ini
0.17/files/docker-entrypoint.sh
0.18/Dockerfile
0.18/files/config.ini
0.18/files/docker-entrypoint.sh

Fixes #317
@bplein I would appreciate if you could test this if it fixes the bug for you and does not create more.

Fix migration when config is mounted

---

0.17/Dockerfile
0.18/Dockerfile

Fix loading of scenarios

---

0.17/files/update-mods.sh
0.18/files/update-mods.sh

Truly fix mod updates with spaces in names

---

README.md
README_zh_CN.md

add zh_CN translation in `README_zh_CN.md` and a link in the original readme to it.

doc: zh_CN translation

---

1.1/Dockerfile

1.1.37 was released today https://forums.factorio.com/viewtopic.php?f=3&t=99501

update to 1.1.37

---

1.1/Dockerfile

1.1.39 was released today https://forums.factorio.com/viewtopic.php?f=3&t=99796

update to 1.1.39

---

README.md

Resolves #391 
This adds a table of the environment variables that are in use as well as listing which image supports them.

add a section to the readme which lists the existing environment variables

---

docker/docker-compose.yml

- Update version to `1.1.59` in `docker-compose.yaml`
- Verified `docker-compose build --no-cache` is successful

Update server version in docker-compose file

---

docker/docker-compose.yml
update.sh

- Modify `update.sh` so that it sets the latest version and SHA in `docker/docker-compose.yml` when new versions are available.
- Update `docker-compose.yml` with the latest stable version. Also, changes formatting for this file, since it was generated with `yq`.
Resolves #448, #421
Let me know if there's anything I need to add.

feat: Auto-update docker-compose.yml

---

buildinfo.json

resolves https://github.com/factoriotools/factorio-docker/issues/479

Update buildinfo.json for new build in 1.1.98

---

docker/Dockerfile
docker/files/docker-entrypoint.sh

A re-raise of #438 by @doridian, rebased on top of latest, with minor changes to reduce image bloat.
Resolves #402
Obsoletes #454

Swap to Debian slim baseimage

---

docker/Dockerfile

Install procps for ps command used in kubernetes probes

---

update.sh

This fixes the issue that `stable-1.2.3` selects version 1.2.3 instead of the one with the `stable` tag

Fixed tag match in update

---

README.md
docker-compose.yml
docker/Dockerfile
docker/files/players-online.sh
docker/rcon/Makefile
docker/rcon/main.c

This adds a minimal rcon client to allow general script usage.
Additionally there is a players-online.sh script to help with automated updates using watchtower.

Add rcon client
